# Jekyll Algolia settings for indexing https://community.algolia.com/jekyll-algolia/options.html
algolia:
  # Index HTML elements, especially code samples.
  nodes_to_index: 'p,li,td,code'
  # Override 10KB default and use our allowed max of 20KB.
  max_record_size: 20000

# Disable the code blocks line numbers at indexing stage
kramdown:
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: false
